# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('curencyAUD', models.FloatField(null=True)),
                ('curencyCAD', models.FloatField(null=True)),
                ('curencyCHF', models.FloatField(null=True)),
                ('curencyCNY', models.FloatField(null=True)),
                ('curencyEUR', models.FloatField(null=True)),
                ('curencyGBP', models.FloatField(null=True)),
                ('curencyNZD', models.FloatField(null=True)),
                ('curencyZAR', models.FloatField(null=True)),
            ],
        ),
    ]
